### ISSUE TITLE
userのidを指定したい

### ISSUE THREAD

**Issue by yashimar** [jphacks/A_2010#6]
今ってuser.idが主キーになっててやり取りもID使ってるよね
けど，ユーザー作るときはIDは指定できなくてメールアドレスだけだから，IDも指定できると嬉しいな
（URLをIDにしようと思っていたので） 
もちろん主キーなので作るときにかぶっていないかチェックする必要はあるけど
by江上

**Comment by tks3141** [comment]
後回しになりました
